name: Lint
on:
  # pull_request:
  #   branches:
  #     - '!main'
  workflow_dispatch:
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm i
      - name: Cache
        uses: actions/cache@v2.1.8
        with:
          path: node_modules
          key: ${{ hashFiles('package-lock.json') }}
      - name: Lint
        run: ./node_modules/.bin/eslint .
